### ISSUE TITLE
Check whether catch (LIB_LA::ApplicationException* e) in the .i file is the correct syntax?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/Libstructural#11]
Check whether catch (LIB_LA::ApplicationException* e) in libstructural.i is the correct syntax, should it be:

catch (LIB_LA::ApplicationException& e)

Same applies to the other exceptions.

**Comment by yosefmaru** [comment]
I changed LIB_LA::ApplicationException* e to LIB_LA::ApplicationException& e and applied the same change on other exceptions.

**Comment by fbergmann** [comment]
looking over this: 

```
%exception {
	 try {
     $action
   } catch (const LIB_LA::ApplicationException& e) {
     SWIG_exception(SWIG_RuntimeError, "app error");
   } catch (LIB_LA::ApplicationException& e) {
		 std::string msg = e->getDetailedMessage();
		 delete e;
   } catch (LIB_LA::NoModelException& e) {
		 std::string msg = e->getMessage();
		 delete e;

     PyErr_SetString (PyExc_Exception, msg.c_str());
	 return NULL;
   } catch (const std::exception& e) {
     SWIG_exception(SWIG_RuntimeError, e.what());
   } catch (...) {
		 SWIG_exception(SWIG_RuntimeError, "Unknown exception");
	 }
}
```

it still seems wrong and inconsistent. Also you cannot delete references. And when you already catch a const exception, that is enough to catch non-const exceptions as well.

**Comment by hsauro** [comment]
I've been reading up on C++ exceptions and you're right we cannot delete
references. I've not worked on this end yet, I think yosef is working on it.

I'm not sure what  constn exception is , must read up on that.

Herbert

**Comment by fbergmann** [comment]
What i meant is that a catch block for `const LIB_LA::ApplicationException& e` will also catch application exceptions without the const attribute. So in one case filing an app error, in the second one only reading a detailed message  (and doing nothing) seemed inconsistent. also the return statement, in just one of the cases seemed strange. 

Ideally also all exceptions would inherit std::exception so that it could get caught readily.
